version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ../:/workspace:cached
  mysql:
    image: mysql:8
    ports:
      - 5001:3306
    volumes:
      - ../.docker/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5002:80
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: password
    depends_on:
      - mysql